development:
  clients:
    unencrypted:
      uri: <%= ENV['ATLAS_URI'] %>/finance_lock_development?retryWrites=true&w=majority
    key_vault:
      # We use the same database for the sake of simplicity, but you should use a different one.
      uri: <%= ENV['ATLAS_URI'] %>/?retryWrites=true&w=majority

    default:
      uri: <%= ENV['ATLAS_URI'] %>/finance_lock_development?retryWrites=true&w=majority
      options:
        auto_encryption_options:
          key_vault_client: 'key_vault'
          key_vault_namespace: 'encryption.__keyVault'
          kms_providers:
            local:
              key: <%= ENV['LOCAL_MASTER_KEY'] %>
          extra_options:
            crypt_shared_lib_path: <%= File.join(Rails.root, 'vendor', 'crypt_shared', 'mongo_crypt_v1.so')  %>
  # Configure Mongoid specific options. (optional)
  options:
    # Preload all models in development, needed when models use inheritance.
    preload_models: true

test:
  clients:
    default:
      database: finance_lock_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
